### ISSUE TITLE
Dropping the '_layer' from abstraction_layer and user_layer packages

### ISSUE THREAD

**Issue by tclose** [INCF/nineml-python#10]
This is a minor issue, but I was wondering whether you would object to dropping the layer suffix from the packages relating to layers. As I am usually a bit frustrated by the time I type 'abstraction' let alone the '_layer' part, and I think it would be pretty obvious at that point that they represent the layer structures (even with less obvious names 'structure', 'property' and 'experiment' in future).

**Comment by jougs** [comment]
I think this is a good idea.

**Comment by iraikov** [comment]
It's an excellent idea, and the abstraction layer needs a more descriptive
name like math or equation.

**Comment by tclose** [comment]
Hi Ivan,

I raised this suggestion (possibly even the same names:) when we were discussing the new layer structure in Gif, but the feeling was that since the abstraction layer was the only layer that was to be left unchanged that it would be confusing to rename it. 

However, I think we probably should have a wider discussion about backwards compatibility at some point, as this something that Erik is very keen to maintain, even though I think most of us were only thinking of it from version 2.0 onwards.

(NB: This should probably be discussed on the INCF/nineml issue tracker instead)

**Comment by apdavison** [comment]
> I am usually a bit frustrated by the time I type 'abstraction' let alone the '_layer' part

This is what tab-completion is for     :wink: 

But seriously, this change is fine with me

**Comment by tclose** [comment]
> This is what tab-completion is for  :wink:

Yeah, that is the only reason it has lasted this long, however, when I am in an environment without tab-completion it drives me batty ;)

> But seriously, this change is fine with me

Okay great.
